### PR TITLE
Autorestock

### PR DESCRIPTION
**Pull request by cheyao**
WIP, do not merge until i say ok in the comments,

currently just made the commands and a little bit of the pathfinding

Made this pull cuz the owner told me to

### CODE REVIEW

**Comment by cheyao** [comment]
don't mind the "o" there just its just a test

**Comment by cheyao** [comment]
burh why there is conflicting files

**Comment by huddy987** [comment]
Try to merge with master, resolve merge conflicts, then push the merge here.

**Comment by cheyao** [comment]
> Try to merge with master, resolve merge conflicts, then push the merge here.

Its sill not finished XD, but should be soon

**Comment by cheyao** [comment]
resolved the conflicts

**Comment by cheyao** [comment]
let me do this again i think i did the wrong branch

**Pull request closed without merging**
